name: barber_shop_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Languages
  intl: ^0.19.0

  # State management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  # Navigation
  auto_route: ^7.8.4

  # UI
  flutter_svg: ^2.0.10+1
  google_fonts: ^4.0.4

  # Utils
  lottie: ^3.1.2
  multiple_result: ^5.1.0
  url_launcher: ^6.1.14
  scroll_to_id: ^1.5.1
  animated_fab_button_menu: ^0.0.2
  carousel_slider: ^5.0.0
  cupertino_icons: any
  firebase_core: 
  firebase_auth: any
  firebase_ui_auth: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^7.3.2
  rename: ^3.0.1
  build_runner: 

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/
  #
  # fonts:
  #   - family: schyler
  #     fonts:
  #       - asset: fonts/schyler-regular.ttf
  #       - asset: fonts/schyler-italic.ttf
  #         style: italic
  #   - family: trajan pro
  #     fonts:
  #       - asset: fonts/trajanpro.ttf
  #       - asset: fonts/trajanpro_bold.ttf
  #         weight: 700
  #
  # for details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
